version: "3.9"

services:

  agentbench-os:
    build:
      context: ../../AgentBench
      dockerfile: src/server/tasks/os_interaction/Dockerfile
    container_name: agentbench_os
    ports:
      - "5001:5021"
    entrypoint: ["python", "-m", "agentrl.worker", "--config", "configs/tasks/os.yaml", "--self", "http://0.0.0.0:5021/api", "os-std"]
    restart: unless-stopped

  agentbench-db:
    build:
      context: ../../AgentBench
      dockerfile: src/server/tasks/dbbench/Dockerfile
    container_name: agentbench_db
    ports:
      - "5002:5021"
    entrypoint: ["python", "-m", "agentrl.worker", "--config", "configs/tasks/db.yaml", "--self", "http://0.0.0.0:5021/api", "db-std"]
    restart: unless-stopped

networks:
  default:
    name: agentbench_net
    driver: bridge
